sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_a91471c056a6_key -iv $encrypted_a91471c056a6_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - tar -xzf credentials.tar.gz
  - mkdir -p lib
  - docker build -t babaolibabo/docker-web -f Dockerfile.dev .
script:
  - docker run babaolibabo/docker-web npm run test -- --coverage
deploy: 
  provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: baboli-deneme
  default: ture
  on: 
    branch: master
